--iKI Tabloyu Birlestirme 

SELECT USERS.* FROM USERS

SELECT USERS.* FROM USERS , ADDRESS WHERE USERS.ID = ADDRESS.USERID

SELECT USERS.* , ADDRESS.ADDRESSTEXT  FROM USERS  , ADDRESS WHERE USERS.ID = ADDRESS.USERID AND USERS.ID = 1

--------------------------------------------------------------------------------------------------------------------------------------
-- TABLO ADINDA AlIAS (AS) KULLANIM

SELECT U.NAMESURNAME ,
U.EMAIL,
U.GENDER,
U.BIRTHDATE,
A.ADDRESSTEXT
FROM USERS U , ADDRESS A
WHERE U.ID = A.USERID 
AND U.ID = 
--------------------------------------------------------------------------------------------------------------------------------------
--SUTUN ISIMLERINDE ALIAS (AS)  KULLANIM

SELECT U.NAMESURNAME AS ADSOYAD,
U.EMAIL MAILADRESI, 
U.GENDER CINSIYET,
U.BIRTHDATE DOGUMTARIHI,
A.ADDRESSTEXT AS ACIKADRES
FROM USERS U , ADDRESS A
WHERE U.ID = A.USERID 
AND U.ID = 1

--------------------------------------------------------------------------------------------------------------------------------------
--BIRDEN FAZLA TABLO BIRLESTIRME  KULLANIM
--ID 1 OLAN 

SELECT U.NAMESURNAME AS ADSOYAD,
U.EMAIL MAILADRESI, 
U.GENDER CINSIYET,
U.BIRTHDATE DOGUMTARIHI,
A.ADDRESSTEXT AS ACIKADRES,
T.TOWN AS KENT,
CT.CITY AS SEHIR,
C.COUNTRY AS ULKE,
D.DISTRICT AS SEMT,
A.POSTALCODE AS POSTAKODU
FROM 
USERS U , ADDRESS A ,COUNTRIES C , CITIES CT , TOWNS T , DISTRICTS D  
WHERE U.ID = A.USERID AND C.ID = A.COUNTRYID  AND CT.ID=A.CITYID AND T.ID = A.TOWNID AND D.ID = A.DISTRICTID AND U.ID = 1

--------------------------------------------------------------------------------------------------------------------------------------
--BIRDEN FAZLA TABLO BIRLESTIRME  KULLANIM
--TUM KAYITLARDA

SELECT U.NAMESURNAME AS ADSOYAD,
U.EMAIL MAILADRESI, 
U.GENDER CINSIYET,
U.BIRTHDATE DOGUMTARIHI,
A.ADDRESSTEXT AS ACIKADRES,
T.TOWN AS KENT,
CT.CITY AS SEHIR,
C.COUNTRY AS ULKE,
D.DISTRICT AS SEMT,
A.POSTALCODE AS POSTAKODU
FROM 
USERS U , ADDRESS A ,COUNTRIES C , CITIES CT , TOWNS T , DISTRICTS D  
WHERE U.ID = A.USERID AND C.ID = A.COUNTRYID  AND CT.ID=A.CITYID AND T.ID = A.TOWNID AND D.ID = A.DISTRICTID
ORDER BY U.NAMESURNAME

--------------------------------------------------------------------------------------------------------------------------------------
--BIRDEN FAZLA TABLO BIRLESTIRME  KULLANIM
--ANKARA SEHRINDE OLAN KAYITLAR

SELECT U.NAMESURNAME AS ADSOYAD,
U.EMAIL MAILADRESI, 
U.GENDER CINSIYET,
U.BIRTHDATE DOGUMTARIHI,
A.ADDRESSTEXT AS ACIKADRES,
T.TOWN AS KENT,
CT.CITY AS SEHIR,
C.COUNTRY AS ULKE,
D.DISTRICT AS SEMT,
A.POSTALCODE AS POSTAKODU
FROM 
USERS U , ADDRESS A ,COUNTRIES C , CITIES CT , TOWNS T , DISTRICTS D  
WHERE U.ID = A.USERID AND C.ID = A.COUNTRYID  AND CT.ID=A.CITYID AND T.ID = A.TOWNID AND D.ID = A.DISTRICTID
AND CT.CITY LIKE 'ANKARA'
ORDER BY U.NAMESURNAME
--------------------------------------------------------------------------------------------------------------------------------------
--ILISIKISEL VERI TABANI UZERINDE DISTINCT KULLANIMI
--
SELECT 
COUNT(DISTINCT U.ID)
FROM 
USERS U , ADDRESS A ,COUNTRIES C , CITIES CT , TOWNS T , DISTRICTS D  
WHERE U.ID = A.USERID AND C.ID = A.COUNTRYID  AND CT.ID=A.CITYID AND T.ID = A.TOWNID AND D.ID = A.DISTRICTID
--------------------------------------------------------------------------------------------------------------------------------------
--ILISIKISEL VERI TABANI UZERINDE GROUP BY - HAVING KULLANIMI
--2 DEN FAZLA OLAN ADRES BILGISI ,ULKEDE,SEHIR LISTELEME

SELECT 
U.NAMESURNAME , COUNT(A.ID) AS ADRESSAYISI , COUNT( C.COUNTRY) ULKESAYISI , COUNT(DISTINCT C.COUNTRY) SEHIRSAYISI
FROM 
USERS U , ADDRESS A ,COUNTRIES C , CITIES CT , TOWNS T , DISTRICTS D  
WHERE U.ID = A.USERID AND C.ID = A.COUNTRYID  AND CT.ID=A.CITYID AND T.ID = A.TOWNID AND D.ID = A.DISTRICTID
GROUP BY U.NAMESURNAME
HAVING COUNT(A.ID)>2

--------------------------------------------------------------------------------------------------------------------------------------
-- SEHIRLERDEKI ADRES BILGISI , KULLANICI SAYISI , ILCELERIN MUSTERELERE GORE DAGILIMI 

SELECT 
CT.CITY , COUNT(U.ID) AS KULLANICISAYISI , COUNT(DISTINCT D.DISTRICT) AS ILCESAYISI
FROM 
USERS U , ADDRESS A ,COUNTRIES C , CITIES CT , TOWNS T , DISTRICTS D  
WHERE U.ID = A.USERID AND C.ID = A.COUNTRYID  AND CT.ID=A.CITYID AND T.ID = A.TOWNID AND D.ID = A.DISTRICTID
GROUP BY CT.CITY
--------------------------------------------------------------------------------------------------------------------------------------



