-- Inner Join / Join  


SELECT 
U.ID,
U.USERNAME_,
A.ADDRESSTEXT
FROM USERS U  JOIN  ADDRESS A ON A.USERID = U.ID   -- HER 2 TABLO KESISENLERI GETIRME


-- LEFT JOIN 

SELECT 
U.ID,
U.USERNAME_,
A.ADDRESSTEXT
FROM USERS U  LEFT  JOIN ADDRESS A ON A.USERID = U.ID   --lEFT JOIN SOLUNDA KALAN KISIM HEPSINI GETIR SAGINDA KALAN ISE KESISIRSE


-- RIGHT JOIN 
SELECT 
U.ID,
U.USERNAME_,
A.ADDRESSTEXT
FROM USERS U  RIGHT  JOIN ADDRESS A ON A.USERID = U.ID  --RIGHT JOIN SAGINDA KALAN KISIM HEPSINI GETIR SOLUNDA KALAN ISE KESISIRSE


--FULL JOIN 

SELECT 
U.ID,
U.USERNAME_,
A.ADDRESSTEXT
FROM USERS U  FULL  JOIN ADDRESS A ON A.USERID = U.ID    --HER 2 TABLOYU TUMUNU GETIRME

